### ISSUE TITLE
DOCS - Added new sections

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-flask-i18n#1]
Hello @b3nhard 

Ty for the work. The project looks good. 
Just to provide a complete guide to the users, please update the new sections added to the DOCS file: 

https://github.com/app-generator/sample-flask-i18n/blob/master/README_i18n.md

- How to specify the default language
- How to correct a wrong label
- How to add a new language

The sections are located at the end of the file. 

ty!

**Comment by b3nhard** [comment]
Finished all the missing parts in the DOCS
